// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::6WheelDriveSubsystemCANJaguar1 = NULL;
CANJaguar* RobotMap::6WheelDriveSubsystemCANJaguar2 = NULL;
CANJaguar* RobotMap::6WheelDriveSubsystemCANJaguar3 = NULL;
CANJaguar* RobotMap::6WheelDriveSubsystemCANJaguar4 = NULL;
RobotDrive* RobotMap::6WheelDriveSubsystemRobotDrive41 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	6WheelDriveSubsystemCANJaguar1 = new CANJaguar(3);
	
	
	6WheelDriveSubsystemCANJaguar2 = new CANJaguar(2);
	
	
	6WheelDriveSubsystemCANJaguar3 = new CANJaguar(4);
	
	
	6WheelDriveSubsystemCANJaguar4 = new CANJaguar(5);
	
	
	6WheelDriveSubsystemRobotDrive41 = new RobotDrive(6WheelDriveSubsystemCANJaguar1, 6WheelDriveSubsystemCANJaguar2,
              6WheelDriveSubsystemCANJaguar3, 6WheelDriveSubsystemCANJaguar4);
	
	6WheelDriveSubsystemRobotDrive41->SetSafetyEnabled(true);
        6WheelDriveSubsystemRobotDrive41->SetExpiration(0.1);
        6WheelDriveSubsystemRobotDrive41->SetSensitivity(0.5);
        6WheelDriveSubsystemRobotDrive41->SetMaxOutput(1.0);


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
